name: ShitCapital XAUVND Tracker

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9,12,15,18 * * *"
      timezone: "Asia/Ho_Chi_Minh"

jobs:
    fetch:
        runs-on: ubuntu-slim
        permissions:
            contents: write
        steps:
        - name: Checkout source code
          uses: actions/checkout@v6
          with:
            ref: data
            persist-credentials: true

        - name: "Set up Python"
          uses: actions/setup-python@v6
          with:
            python-version-file: ".python-version"

        - name: Install uv
          uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b

        - name: Install dependencies
          run: uv sync --frozen

        - name: Fetch data
          run: python3 fetch.py

        - name: Sync data
          uses: stefanzweifel/git-auto-commit-action@v7
          with:
            branch: data
            commit_message: updates Vũ status on the centralized database
            commit_user_name: Thanh Do Phung
            commit_user_email: phungthanhdo@shitcapital.com.vn
            commit_author: Thanh Do Phung <phungthanhdo@shitcapital.com.vn>
            push_options: "--force"
