name: ShitCapital XAUVND Tracker

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9,12,15,18 * * *"
      timezone: "Asia/Ho_Chi_Minh"

jobs:
    fetch:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
        - name: Checkout main source code
          uses: actions/checkout@v6
          with:
            ref: main
            persist-credentials: true

        - name: "Set up Python"
          uses: actions/setup-python@v6
          with:
            python-version: "3.12"

        - name: Install uv
          uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b

        - name: Install dependencies
          run: uv sync

        - name: Checkout data
          uses: actions/checkout@v6
          with:
            ref: data
            persist-credentials: true

        - name: Fetch data
          run: |
            python3 -c "print('\n\n'.join([''.join(c['source']) for c in __import__('json').loads(r'''$(curl https://raw.githubusercontent.com/SpikeVN/golddb/refs/heads/main/fetch.ipynb)''')['cells'] if c['cell_type'] == 'code']))" > ./fetch.py
            uv run fetch.py
            rm fetch.py pyproject.toml

        - name: Sync data
          uses: stefanzweifel/git-auto-commit-action@v7
          with:
            branch: data
            commit_message: updates Vũ status on the centralized database
            commit_user_name: Thanh Do Phung
            commit_user_email: phungthanhdo@shitcapital.com.vn
            commit_author: Thanh Do Phung <phungthanhdo@shitcapital.com.vn>
